###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:5.5
      container_name: mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbpass
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpass
      ports:
        - "3306:3306"
